sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Pt7j+2kWB2fDZSjE0eiEK5B5zeJc8hnkyenwRIWJWXbU5pbwNrtSUf3xmkNitQNXyuSU57mgy2/goo0CjI5KV8Cb4Y5zfAWPaA4vQ/xp+YbtipoNp5vSbjIAC0y8DVunsyqZZ5LBSz28P5fP8LQUUL2LGze96HSO1k6n0D5RB8RufVuSgR6KWr69GgvS4Z3Jgm6mK7t0prVOFeJeauFRxTAhMbASOaj5gEMve1GF0gfQCJQFGxcsMbgTf7QMOvGx8dtkulCdjcN20H/4AiK1bqapwk0587iU/mYX3TMFVKnE5hzYD8a68VPfKXXB/Ca6RWkONAEu04c48IRavt9hhX9Lq7pq3F4WJEG0Su0XALMdWEQdTkmtLFkWdlGOIzIBiMSho3+XBiCUOl7crxIunzXVijmasTvRKC4NqZkEi7c7vGfOEhU4XEQ7xgVyIoMKGWEM3Ye+AL+AkibvWf1fUOEGEQhHukpB3xEjeAL7M2rHmmY09H0RxEYw4AAYsP9oTNl6F2RKSZMCtZE+XC6Whc8rLGKHhJLA1nCcfs3v5Gy+kBM6Mzaow2XKQyM8elh+OK8bXg8xtbJzHnYkRxbekwAvqd47aXh/iPb43IRWRsquZCdVTiAyz/7tdPJO68idURBuC1ZTdpaBL1V1pQJ2pPnLDdG7kJlYO6JFre15H90=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Lizzie-Leigh_2521
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy